name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files to VPS
      run: |
        scp -r ./ rootame@38.242.214.122:/tradingtantra

    - name: Restart Nginx
      run: |
        ssh rootame@38.242.214.122 'sudo systemctl restart nginx'
