export const tickerSymbol = [
  { proName: "AUROPHARMA", description: "Aurobindo Pharma" },
  { proName: "AXISBANK", description: "Axis Bank" },
  { proName: "BAJAJFINSV", description: "Bajaj Finserv" },
  { proName: "BAJFINANCE", description: "Bajaj Finance" },
  { proName: "AARTIIND", description: "Aarti Industries" },
  { proName: "ABB", description: "ABB" },
  { proName: "ABCAPITAL", description: "Aditya Birla Capital" },
  { proName: "ACC", description: "ACC" },
  { proName: "ADANIENSOL", description: "Adani Energy Solutions" },
  { proName: "ADANIENT", description: "Adani Enterprises" },
  { proName: "ADANIGREEN", description: "Adani Green Energy" },
  { proName: "ADANIPORTS", description: "Adani Ports & SEZ" },
  { proName: "ALKEM", description: "Alkem Laboratories" },
  { proName: "AMBUJACEM", description: "Ambuja Cements" },
  { proName: "BALKRISIND", description: "Balkrishna Industries" },
  { proName: "ANGELONE", description: "Angel One" },
  { proName: "APLAPOLLO", description: "APL Apollo Tubes" },
  { proName: "APOLLOHOSP", description: "Apollo Hospitals" },
  { proName: "APOLLOTYRE", description: "Apollo Tyres" },
  { proName: "ASHOKLEY", description: "Ashok Leyland" },
  { proName: "ASIANPAINT", description: "Asian Paints" },
  { proName: "ASTRAL", description: "Astral" },
  { proName: "ABFRL", description: "Aditya Birla Fashion" },
  { proName: "ATGL", description: "Adani Total Gas" },
  { proName: "AUBANK", description: "AU Small Finance Bank" },
  { proName: "BANDHANBNK", description: "Bandhan Bank" },
  { proName: "BANKBARODA", description: "Bank of Baroda" },
  { proName: "BANKINDIA", description: "Bank of India" },
  { proName: "BEL", description: "Bharat Electronics" },
  { proName: "BERGEPAINT", description: "Berger Paints" },
  { proName: "BHARATFORG", description: "Bharat Forge" },
  { proName: "BHARTIARTL", description: "Bharti Airtel" },
  { proName: "BHEL", description: "Bharat Heavy Electricals" },
  { proName: "BIOCON", description: "Biocon" },
  { proName: "BOSCHLTD", description: "Bosch" },
  { proName: "BPCL", description: "Bharat Petroleum" },
  { proName: "BRITANNIA", description: "Britannia Industries" },
  { proName: "BSE", description: "BSE" },
  { proName: "BSOFT", description: "Birlasoft" },
  { proName: "CAMS", description: "Computer Age Management Services" },
  { proName: "CANBK", description: "Canara Bank" },
  { proName: "CDSL", description: "CDSL" },
  { proName: "CESC", description: "CESC" },
  { proName: "CGPOWER", description: "CG Power & Industrial Solutions" },
  { proName: "CHAMBLFERT", description: "Chambal Fertilisers & Chemicals" },
  { proName: "CHOLAFIN", description: "CHOLAMANDALAM IN & FIN CO" },
  { proName: "CIPLA", description: "Cipla" },
  { proName: "COALINDIA", description: "Coal India" },
  { proName: "COFORGE", description: "Coforge" },
  { proName: "COLPAL", description: "Colgate Palmolive" },
  { proName: "CONCOR", description: "Container Corporation of India" },
  { proName: "CROMPTON", description: "Crompton Greaves" },
  { proName: "CUMMINSIND", description: "Cummins" },
  { proName: "EICHERMOT", description: "Eicher Motors" },
  { proName: "DABUR", description: "Dabur" },
  { proName: "DALBHARAT", description: "Dalmia Bharat" },
  { proName: "DEEPAKNTR", description: "Deepak Nitrite" },
  { proName: "PNB", description: "Punjab National Bank" },
  { proName: "POLICYBZR", description: "PB FinTech" },
  { proName: "RBLBANK", description: "RBL Bank" },
  { proName: "RECLTD", description: "Rural Electrification Corporation" },
  { proName: "DELHIVERY", description: "Delhivery" },
  { proName: "EXIDEIND", description: "Exide Industries" },
  { proName: "POLYCAB", description: "Polycab" },
  { proName: "POONAWALLA", description: "Poonawalla Fincorp" },
  { proName: "POWERGRID", description: "Power Grid Corporation of India" },
  { proName: "PRESTIGE", description: "Prestige Estate" },
  { proName: "RAMCOCEM", description: "Ramco Cements" },
  { proName: "DIXON", description: "Dixon Technologies" },
  { proName: "DMART", description: "Avenue Supermarts DMart" },
  { proName: "CYIENT", description: "Cyient" },
  { proName: "DRREDDY", description: "Dr Reddys Laboratories" },
  { proName: "DIVISLAB", description: "Divis Laboratories" },
  { proName: "ESCORTS", description: "Escorts Kubota" },
  { proName: "DLF", description: "DLF" },
  { proName: "FEDERALBNK", description: "Federal Bank" },
  { proName: "GAIL", description: "GAIL" },
  { proName: "GLENMARK", description: "Glenmark Pharmaceuticals" },
  { proName: "GMRAIRPORT", description: "GMR Airports" },
  { proName: "GODREJCP", description: "Godrej Consumer Products" },
  { proName: "GODREJPROP", description: "Godrej Properties" },
  { proName: "GRANULES", description: "Granules" },
  { proName: "GRASIM", description: "Grasim Industries" },
  { proName: "HAL", description: "Hindustan Aeronautics" },
  { proName: "HAVELLS", description: "Havells" },
  { proName: "HCLTECH", description: "HCL Technologies" },
  { proName: "HDFCAMC", description: "HDFC AMC" },
  { proName: "HDFCBANK", description: "HDFC Bank" },
  { proName: "HDFCLIFE", description: "HDFC Life Insurance" },
  { proName: "HEROMOTOCO", description: "Hero Motocorp" },
  { proName: "HFCL", description: "HFCL" },
  { proName: "HINDALCO", description: "Hindalco Industries" },
  { proName: "HINDCOPPER", description: "Hindustan Copper" },
  { proName: "HINDPETRO", description: "Hindustan Petroleum" },
  { proName: "HINDUNILVR", description: "Hindustan Unilever" },
  { proName: "HUDCO", description: "HUDCO" },
  { proName: "ICICIBANK", description: "ICICI Bank" },
  { proName: "ICICIGI", description: "ICICI Lombard General Insurance" },
  { proName: "ICICIPRULI", description: "ICICI Prudential Life Insurance" },
  { proName: "IDEA", description: "Vodafone Idea" },
  { proName: "IDFCFIRSTB", description: "IDFC First Bank" },
  { proName: "IEX", description: "Indian Energy Exchange" },
  { proName: "IGL", description: "Indraprastha Gas" },
  { proName: "IIFL", description: "IIFL Finance" },
  { proName: "INDHOTEL", description: "Indian Hotels Company" },
  { proName: "INDIANB", description: "Indian Bank" },
  { proName: "INDIGO", description: "Interglobe Aviation" },
  { proName: "INDUSINDBK", description: "Indusind Bank" },
  { proName: "INDUSTOWER", description: "Indus Towers" },
  { proName: "INFY", description: "Infosys" },
  { proName: "IOC", description: "Indian Oil Corporation" },
  { proName: "IRB", description: "IRB Infrastructure Developers" },
  { proName: "IRCTC", description: "IRCTC" },
  { proName: "IREDA", description: "IREDA" },
  { proName: "IRFC", description: "IRFC" },
  { proName: "ITC", description: "ITC" },
  { proName: "JINDALSTEL", description: "Jindal Steel" },
  { proName: "JIOFIN", description: "Jio Financial Services" },
  { proName: "JKCEMENT", description: "JK Cement" },
  { proName: "JSL", description: "Jindal Stainless" },
  { proName: "JSWENERGY", description: "JSW Energy" },
  { proName: "JSWSTEEL", description: "JSW Steel" },
  { proName: "JUBLFOOD", description: "Jubilant FoodWorks" },
  { proName: "KALYANKJIL", description: "Kalyan Jewellers" },
  { proName: "KEI", description: "KEI Industries" },
  { proName: "KOTAKBANK", description: "Kotak Bank" },
  { proName: "KPITTECH", description: "KPIT Technologies" },
  { proName: "LAURUSLABS", description: "Laurus Labs" },
  { proName: "LICHSGFIN", description: "LIC Housing Finance" },
  { proName: "LICI", description: "LIC of India" },
  { proName: "LODHA", description: "Macrotech Developers" },
  { proName: "LT", description: "Larsen & Toubro" },
  { proName: "NMDC", description: "NMDC" },
  { proName: "PIDILITIND", description: "Pidilite Industries" },
  { proName: "PIIND", description: "PI Industries" },
  { proName: "RELIANCE", description: "Reliance Industries" },
  { proName: "SAIL", description: "Steel Authority of India" },
  { proName: "SBICARD", description: "SBI Cards" },
  { proName: "SBILIFE", description: "SBI Life Insurance" },
  { proName: "SBIN", description: "State Bank of India" },
  { proName: "SHREECEM", description: "Shree Cement" },
  { proName: "LTF", description: "L&T Finance" },
  { proName: "LTIM", description: "LTI Mindtree" },
  { proName: "LTTS", description: "L&T Technology Services" },
  { proName: "LUPIN", description: "Lupin" },
  { proName: "M&M", description: "Mahindra & Mahindra" },
  { proName: "M&MFIN", description: "M&M Financial Services" },
  { proName: "MANAPPURAM", description: "Manappuram Finance" },
  { proName: "MARICO", description: "Marico" },
  { proName: "MARUTI", description: "Maruti Suzuki" },
  { proName: "MAXHEALTH", description: "Max Healthcare Institute" },
  { proName: "MCX", description: "MCX" },
  { proName: "MFSL", description: "Max Financial Services" },
  { proName: "MGL", description: "Mahanagar Gas" },
  { proName: "MOTHERSON", description: "SAMVARDHANA MOTHERSON INT" },
  { proName: "MPHASIS", description: "Mphasis" },
  { proName: "MRF", description: "MRF" },
  { proName: "MUTHOOTFIN", description: "Muthoot Finance" },
  { proName: "NATIONALUM", description: "NALCO" },
  { proName: "NAUKRI", description: "Info Edge" },
  { proName: "NBCC", description: "NBCC" },
  { proName: "NCC", description: "Nagarjuna Construction Company" },
  { proName: "NESTLEIND", description: "Nestle" },
  { proName: "NHPC", description: "NHPC" },
  { proName: "SHRIRAMFIN", description: "Shriram Finance" },
  { proName: "SIEMENS", description: "Siemens" },
  { proName: "SJVN", description: "SJVN" },
  { proName: "SOLARINDS", description: "Solar Industries" },
  { proName: "SONACOMS", description: "Sona BLW Precision Forgings" },
  { proName: "SRF", description: "SRF" },
  { proName: "SUNPHARMA", description: "Sun Pharmaceutical" },
  { proName: "SUPREMEIND", description: "Supreme Industries" },
  { proName: "SYNGENE", description: "Syngene International" },
  { proName: "TATACHEM", description: "Tata Chemicals" },
  { proName: "UPL", description: "UPL" },
  { proName: "VBL", description: "Varun Beverages" },
  { proName: "VEDL", description: "Vedanta" },
  { proName: "VOLTAS", description: "Voltas" },
  { proName: "WIPRO", description: "Wipro" },
  { proName: "YESBANK", description: "Yes Bank" },
  { proName: "ZOMATO", description: "Zomato" },
  { proName: "ZYDUSLIFE", description: "Zydus Life Science" },
  { proName: "TATACOMM", description: "Tata Communications" },
  { proName: "TITAN", description: "Titan" },
  { proName: "TORNTPHARM", description: "Torrent Pharmaceuticals" },
  { proName: "TORNTPOWER", description: "Torrent Power" },
  { proName: "TRENT", description: "Trent" },
  { proName: "NTPC", description: "NTPC" },
  { proName: "NYKAA", description: "Nykaa" },
  { proName: "OBEROIRLTY", description: "Oberoi Realty" },
  { proName: "OFSS", description: "Oracle Financial Services Software" },
  { proName: "OIL", description: "Oil India" },
  { proName: "ONGC", description: "Oil & Natural Gas Corporation" },
  { proName: "PAGEIND", description: "Page Industries" },
  { proName: "PATANJALI", description: "Patanjali Foods" },
  { proName: "PAYTM", description: "One97 Communications" },
  { proName: "PEL", description: "Piramal Enterprises" },
  { proName: "PERSISTENT", description: "Persistent Systems" },
  { proName: "PETRONET", description: "Petronet LNG" },
  { proName: "PFC", description: "Power Finance Corporation" },
  { proName: "PHOENIXLTD", description: "Phoenix Mills" },
  { proName: "TVSMOTOR", description: "TVS Motors" },
  { proName: "ULTRACEMCO", description: "UltraTech Cement" },
  { proName: "UNIONBANK", description: "Union Bank of India" },
  { proName: "TATACONSUM", description: "Tata Consumer Products" },
  { proName: "TATAELXSI", description: "Tata Elxsi" },
  { proName: "TATAMOTORS", description: "Tata Motors" },
  { proName: "TATAPOWER", description: "Tata Power" },
  { proName: "TATASTEEL", description: "Tata Steel" },
  { proName: "TATATECH", description: "Tata Technologies" },
  { proName: "TCS", description: "Tata Consultancy Services" },
  { proName: "TECHM", description: "Tech Mahindra" },
  { proName: "TIINDIA", description: "Tube Investment" },
  { proName: "TITAGARH", description: "Titagarh Rail Systems" },
  { proName: "UNITDSPR", description: "United Spirits" },
];
